version "4.14"

// Peppergrinder
#include "zscript/Trog_Zombies.zsc"
#include "zscript/Greely_Shotgunners.zsc"
#include "zscript/Vera_Chaingunners.zsc"

// Icarus Innovations
#include "zscript/PD42_Zombies.zsc"
#include "zscript/UMP_Machinegunner.zsc"
#include "zscript/USP_Homeboy.zsc"
#include "zscript/Frontiersman_Zombieman.zsc"

// Misc
#include "zscript/Altis_Shotgunner.zsc"
#include "zscript/Winged_Babuins.zsc"

#include "zscript/Event_handler.zsc"